# Clean and don't fail
install:
  - rm -rf public

# Build the website
script:
  - ./exec/hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  fqdn: eazurich.org
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
